# Generated by Django 5.0.6 on 2025-02-18 01:15

import django.db.models.deletion
import encrypted_model_fields.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', encrypted_model_fields.fields.EncryptedTextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US')),
                ('symptom', models.TextField()),
                ('onset', models.CharField(choices=[('sudden', 'Sudden'), ('gradual', 'Gradual')], max_length=20)),
                ('duration', models.CharField(max_length=100)),
                ('worse_factors', models.TextField(verbose_name='Things that make it worse')),
                ('better_factors', models.TextField(verbose_name='Things that make it better')),
                ('pattern', models.CharField(choices=[('constant', 'Constant'), ('waves', 'Comes in Waves')], max_length=20)),
                ('possible_cause', models.TextField(blank=True, null=True, verbose_name='Any idea what could be causing it')),
                ('concerns', models.TextField(blank=True, null=True, verbose_name='Any specific concerns about the symptoms')),
                ('doctor_expectation', models.TextField(verbose_name='What expectation do you want your family doctor to meet?')),
                ('medication_allergy', models.TextField(blank=True, null=True, verbose_name='Do you have any medication allergy?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('encrypted_url', models.CharField(blank=True, max_length=255, null=True)),
                ('access_attempts', models.IntegerField(default=3)),
            ],
            options={
                'verbose_name_plural': 'Health Form',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sender_type', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='admin', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encrypted_reply_url', models.CharField(blank=True, max_length=255, null=True)),
                ('reply_attempts', models.IntegerField(default=3)),
                ('health', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Core.health')),
                ('parent_reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Core.reply')),
            ],
            options={
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
